packages:
  - "apps/api"
  - "apps/docs"
  - "apps/proxy"
  - "apps/tests"
  - "apps/webapp"
  - "apps/examples/*"
  - "packages/*"

overrides:
  zod: ^4.1.12
  react: ^19.1
  react-dom: ^19.1

patchedDependencies:
  ai@6.0.158: patches/ai@6.0.158.patch

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - protobufjs
  - sharp

allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  protobufjs: true
  sharp: true
