services:
  postgres-db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s

  api:
    image: ${AGENTVIEW_API_IMAGE}
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}
      AGENTVIEW_STUDIO_URL: ${AGENTVIEW_STUDIO_URL}
    ports:
      - "8080:80"
    depends_on:
      postgres-db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped

volumes:
  pgdata: