services:
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: rudzienki/agentview-api:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      STUDIO_URL: http://localhost:1989
    ports:
      - "8080:8080"    
    depends_on:
      - postgres-db
    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped

volumes:
  pgdata: