// Generated by eve. Do not edit by hand.
import { POST } from "./workflows.mjs";
import { getWorld as __eveGetWorkflowWorld } from "/Users/andrzej/Projects/agentview/agentview/apps/examples/eve-in-next/node_modules/.pnpm/eve@0.11.10_ai@7.0.0-beta.178_zod@4.4.3__jiti@2.7.0_next@16.2.9_@babel+core@7.29.7_reac_c144c8688908472f3895ad95b536d788/node_modules/eve/dist/src/compiled/@workflow/core/runtime.js";

try {
  const __eveWorkflowWorld = await __eveGetWorkflowWorld();
  if (typeof __eveWorkflowWorld?.registerHandler === "function") {
    __eveWorkflowWorld.registerHandler("__eve_wkf_workflow_", POST);
  }
} catch (err) {
  console.warn("[eve] Failed to register direct workflow queue handlers:", err);
}

export default async ({ req }) => {
  return await POST(req);
};
