services:
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5433:80"   # Expose pgAdmin on localhost:5433
    depends_on:
      - postgres-db
    volumes:
      - ./docker/pg-admin/servers.json:/pgadmin4/servers.json

  api:
    build: .
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      STUDIO_URL: http://localhost:1989
    ports:
      - "8080:8080"    
    depends_on:
      - postgres-db
    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped

volumes:
  pgdata: